development: &defaults
  adapter: mysql2
  encoding: utf8mb4
  database: blog
  username: root
  password: root
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: exchange_app_test

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: blog
  username: root
  password: root
  pool: 10
  reconnect: true

staging:
  adapter: mysql2
  encoding: utf8mb4
  database: blog
  username: root
  password: root
  pool: 10
  reconnect: true
